AravisProject/aravis

viewer/arvviewer.c
Instead of printing that the user interface file is missing, print the actual error.
E.g. on Ubuntu 14.04 with gtk+ 3.10 it will now print the more informative message:
```
Cant't load user interface file ('/usr/local/share/aravis-0.6/arv-viewer.ui'): /usr/local/share/aravis-0.6/arv-viewer.ui: required gtk+ version 3.12, current version is 3.10
```
=> print more descriptive error if user interface file can't be loaded

configure.ac
This adds a new option to the configure script (--enable-fast-heartbeat) that defines the ARAVIS_FAST_HEARTBEAT in src/arvgvdevice.h thus enabling the much faster heartbeat option.
refs #13
=> Allows to enable the fast heartbeat flag from the configuration script

src/arvfakegvcamera.c
Three changes related to handling of Control Channel Privilege register in the fake camera.
The main change is to correctly handle a client which explicitly relinquishes control privilege by writing CCP=0.  This needs to clear ```gv_camera->controller_address``` so the the write permission check works correctly.
I found this when writing some test code which needs to pass control between two clients: some setup code, and the code under test.  With these changes, this hand off works correctly.
I will note that when ```!write_access``` it would be better to return a permission denied error (I think involving ```ARV_GVCP_PACKET_TYPE_ERROR```).  However, I couldn't find an easy way to do this.
=> Fake camera controller privilege fixups

README.md
I found that after running `brew install gettext intltool gtk-doc` I was missing the `aclocal` command. Installing `automake` with brew solves this issue.
=> Adds automake to list of brew install programs

src/arvcamera.c
The old version didn't work for Basler acA4112-30um.
=> actually check for availability of binning

src/arvgvdevice.c
If arv_device_set_integer_feature_value(device, "GevSCPSPacketSize", current_size) fails for some reason current_size will stay the same and the surrounding loop will never terminate. This patch adds a check that terminates the loop if current_size does not change from one loop iteration to the next.
An alternative to this patch would be to limit the number of outer loop iterations.
=> avoid infinite loop in auto packet size

src/arvgvinterface.c, src/arvgvinterfaceprivate.h
This makes discovery work for all the GV devices on networks containing
moderately large numbers of them (in my testing, around 23-24 of them).
=> Set SO_RCVBUF size to a larger value on discovery socket.

src/arvgc.c
I came across the need for this when trying to access UserFile1 on a Point Grey Blackfly S.
=> Properly interpret "Register" nodes

src/arvdevice.c
This PR should resolve issues with `arv_device_get_status` almost always returning ARV_DEVICE_STATUS_SUCCESS
I guess this also closes https://github.com/AravisProject/aravis/issues/177
=> bugfix: device status always set to ARV_DEVICE_STATUS_SUCCESS

src/arvcamera.c
For example, if camera has Height==MAX_HEIGHT, we can not set OffsetY>0,
so we need set width and height first, and set offsets then.
=> change order of operations in arv_camera_set_region 

src/arvuvstream.c
For some cameras the SI info register is zero, which not handles correctly. This PR fixes the alignment and the assert.
=> Fixed align assert and handle alignment of zero correctly.

src/arvgvfakecamera.c
multiple fake cameras on the same system.
I have just marked the global discovery socket as reusable, which allows multiple cameras provided they are bound to different interfaces. IIUC correctly, Linux will shard the incoming UDP messages across processes - I tested this with arv_viewer, arv-fake-camera and another camera simulator I have written for my own purposes, and that works. Two instances of arv-fake-camera do not show up in the viewer because they both have the same serial number (GV01). Perhaps we can add the interface name somehow into the mix to distinguish them.
=> global discovery socket needs to be marked SO_REUSEPORT to allow

viewer/meson.build
"appdata" is the legacy path for AppStream files, and now such directory should be called "metainfo".
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps
=> viewer: Store appstream file in metainfo dir

COPYING
This PR changes COPYING to the LGPL 2+ (version 2.1 to be precise, which is the first release of the LGPL). As discussed in #307.
Text taken from: https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt
=> Change COPYING to LGPL2.1.

src/arvgvstream.c
With this change, ArvGvStream will discard duplicate packets
for packet_ids already received. The previous behaviour was
to use the payload from the duplicate packet, replacing the
previously received data.
Discarding duplicate packets acts as a workaround for an
issue with PtGrey BlackFly cameras which sometimes send
duplicate packets with incorrect data.
See issue #311
=> Ignore duplicate packets in ArvGvStream

docs/reference/aravis/aravis-sections.txt, src/arvcamera.c, src/arvcamera.h, src/arvgcboolean.c, src/arvgcboolean.h, tests/exception.py
The function gc_boolean_get_value take a GError ** and it returns a
boolean, but the return value doesn't indicate if the function call
failed. The result is that the automatically generated bindings assume
there is no data in the return value. In Rust, that translates to a
Result with no value.
Fix the binding by implementing functions taking an ouput parameter, and
using rename-to annotation to replace the functions designed for C use.
=> introspection: workaround binding issue of boolean returning functions

viewer/arvviewer.c
Already exist below:
viewer/arvviewer.c:926:        auto_exposure = arv_camera_get_gain_auto (viewer->camera, NULL) != ARV_AUTO_OFF;
viewer/arvviewer.c:965:        auto_gain = arv_camera_get_gain_auto (viewer->camera, NULL) != ARV_AUTO_OFF;
=> remove redundant and erroneous code

meson.build, src/meson.build
- Add missing include dir to the declared dependency
- Clean up required libraries in pkgconfig generation since meson is  smart enough to do that for us.
.pc diff (meson 0.54.0):
```diff
8,10c8,11
< Requires: glib-2.0 gobject-2.0 gio-2.0
< Requires.private: glib-2.0 >= 2.44, gobject-2.0, gio-2.0, libxml-2.0, zlib, libusb-1.0, libxml-2.0 zlib libusb-1.0
< Libs: -L${libdir} -laravis-0.8 -lm
---
> Requires: glib-2.0 >= 2.44, gobject-2.0, gio-2.0
> Requires.private: libxml-2.0, zlib, libusb-1.0
> Libs: -L${libdir} -laravis-0.8
> Libs.private: -lm
```
This also fixes a deprecation warning:
```
subprojects/aravis/src/meson.build:256: DEPRECATION: Library aravis-0.8 was passed to the "libraries" keyword argument of a previous call to generate() method instead of first positional argument. …
```
=> meson: fix issues when used as a subproject

src/arvcamera.c, src/arvgvfakecamera.c, src/arvmisc.c, src/arvstream.c
Most of the reported issues are false-positives. The remaining ones
consist of dead code, uninitialized values and one memory leak.
=> all: fix issues reported by Clang static analyzer

src/arvinterface.c
Fixed a couple of typos in the ArvInterface description.
Mostly for `ArvCamera` -> `ArvInterface`.
=> interface: fix typos in documentation

meson.build
Despite the fact that libusb is an optional dependency, it looks like the viewer is not built if libusb is not found. The proposed solution is to add usb to `aravis_dependencies` only if it was found. I'm not familiar with meson so it may not be the most elegant solution though.
=> build: allow to build arv-viewer without optional libusb

src/arv-fake-camera.xml, src/arvfakecamera.c, tests/fake.c
Adds support for all Bayer formats to the `arv-fake-gv-camera` utility.
Closes #354
=> arvfakecamera: implement Bayer pixel formats

gst/gstaravis.c, gst/gstaravis.h
The packet delay is reset on SVS-VISTEK eco424CVGE and exo304CGETR cameras
when GevCCP access is released. Must set it while holding the control
access.
This adds a property as the features property would be more difficult due to the scaling by GevTimestampTickFrequency.
=> gst: Add packet-delay property

gst/gstaravis.c
SVS-Vistek cameras reset Width and Height when PixelFormat is set. With the old initialization order the region was always max size regardless of width and height in caps.
=> gst: Set pixel format before binning and region

gst/gstaravis.c, gst/gstaravis.h
Reading properties from camera in gst_aravis_init_camera overwrites
properties set on launch string.
Fixes #357
=> gst: Fix auto gain, exposure and binning on init

gst/gstaravis.c
I found the aravissrc used a lot of memory that increased when the camera connection had problems and new streams were started. It turned out to relate to missing error handling where no element errors were posted to inform the application it should clean up.
While looking at it I also noticed the object should have locking.
As I fixed them before I had sent a PR for the Enum as mentioned in #360 and I tested them together, I put them all in one pull request. They touch so much the same code they are not completely independent.
=> Change gain-auto and exposure-auto to GstArvAuto Enum, add error handling and locking

docs/arv-tool-0.8.1, src/arvdomimplementation.c, src/arvgcpropertynode.c, src/arvgcstructentrynode.c, src/arvgvdevice.c, src/arvtool.c, src/arvuvstream.c
Debian linter highlighted some common misspellings in the binaries.
"endianess" still reads in the API, but this does not change API.
=> Fix spelling available, Unknown, endianness

gst/gstaravis.c, src/arvcamera.c
I found the aravissrc in deadlock. Unfortunately I was unable to capture the exact position where it had deadlocked and did not manage to reproduce it, but found some locking omissions through review.
I tried to see if the `gst_aravis_create` could be made to come out from the `arv_stream_timeout_pop_buffer` without delay, but I did not see an interface to tell the stream should stop now. This would be useful if there is need to stop fast. A look at it resulted in some minor cleanups that change no functionality.
I also found some spelling mistakes. Rather than put in own PR, I try if I can save some effort and offer them in this same PR. I'll split to separate PR if that is more convenient.
=> GStreamer Aravissrc plugin deadlocked

gst/gstaravis.c, gst/gstaravis.h
GstBaseSrc implements num-buffers property already and this prevents that functionality. Using own name we get to limit the number of frames captured with num-buffers, as expected.
=> gst: Rename num-buffers to arv-buffers

src/arvgcfeaturenode.c, src/arvgcfeaturenode.h
This function is useful for retrieving feature node name space value.
In some cases camera manufacturers do not give detailed display text or description text for some standard feature nodes. By checking feature name and also if standard name space is used in particular feature, we can add our own display text. This is the basic use case.
=> Implements arv_gc_feature_node_get_name_space() function.

docs/reference/aravis/aravis-sections.txt, src/arvgc.c, src/arvgcconverter.c, src/arvgcconverternode.c, src/arvgcconverterprivate.h, src/arvgcenums.h, src/arvgcfloat.c, src/arvgcfloat.h, src/arvgcfloatnode.c, src/arvgcfloatregnode.c, src/arvgcintconverternode.c, src/arvgcinteger.c, src/arvgcinteger.h, src/arvgcintegernode.c, src/arvgcintregnode.c, src/arvgcmaskedintregnode.c, src/arvgcpropertynode.c, src/arvgcpropertynode.h, src/arvgcstructentrynode.c
This commit adds support for Representation property nodes which specify how integer and float values should be shown to user (e.g. as hex values).
From limited testing it seems that everything works, but testing/review would be much appreciated. Unit tests succeed, but I have not added extra tests for checking representation property.
I have used both `error` and `default_value` style functions. The `ArvGc*Interface` methods all have `error` parameters so I followed that with `get_representation` functions. However in `arv_gc_property_node_get_representation` I used `default_value` to match other property node functions. The result is that `get_representation` really never throws an error and silently returns `ARV_GC_REPRESENTATION_UNDEFINED` on errors. The default value for all nodes is …
=> genicam: add 'Representation' property node support

docs/reference/aravis/aravis-sections.txt, src/arvgcenums.h, src/arvgcfeaturenode.c
The `ArvGcNameSpace` enum and respective feature node function was added in PR #379. However, the documentation was missing which is now added in this patch.
=> genicam: add documentation related to ArvGcNameSpace

src/arvgcintswissknifenode.c, src/arvgcswissknife.c, src/arvgcswissknifenode.c, src/arvgcswissknifeprivate.h
This does not change public API, but interface functions are now able to get SwissKnife and IntSwissKnife Unit and Representation node info.
=> genicam: add 'Representation' and 'Unit' property node support for swiss knife

docs/reference/aravis/aravis-sections.txt, src/arvgc.c, src/arvgcconverter.c, src/arvgcconverternode.c, src/arvgcconverterprivate.h, src/arvgcdefaultsprivate.h, src/arvgcenums.h, src/arvgcfloat.c, src/arvgcfloat.h, src/arvgcfloatnode.c, src/arvgcfloatregnode.c, src/arvgcpropertynode.c, src/arvgcpropertynode.h, src/arvgcswissknifenode.c, src/meson.build
This patch adds many things related to 'DisplayNotation' and 'DisplayPrecision' nodes. Public API is expanded by `ArvGcDisplayNotation` enum, `*_get_display_notation`, `*_get_display_precision`, `arv_gc_property_node_new_display_notation` and `arv_gc_property_node_new_display_precision` functions.
=> genicam: add 'DisplayNotation' and 'DisplayPrecision' property node support

docs/reference/aravis/aravis-sections.txt, src/arvgcenums.h
Adds some documentation strings for Genicam enums and also fixes a bug by renaming `ArvGcSign` to `ArvGcSignedness`.
=> arvgcenums: add more documentation for Genicam enums

docs/reference/aravis/aravis-sections.txt, src/arvgcboolean.c, src/arvgccommand.c, src/arvgcconverter.c, src/arvgcenumeration.c, src/arvgcfeaturenode.c, src/arvgcfeaturenode.h, src/arvgcfloatnode.c, src/arvgcintegernode.c, src/arvgcpropertynode.c, src/arvgcregisternode.c, src/arvgcstructentrynode.c, src/arvgcswissknife.c
This commit implements Genicam access mode retrieval for all important features except `StructEntry` nodes.
1. In case we have a register node we get the `access_mode` property and we are done.
2. If we have non-register feature node then `arv_gc_feature_node_get_access_mode` utilizes bunch of new private functions like `arv_gc_integer_node_get_access_mode`, `arv_gc_enumeration_get_access_mode` etc. to get the referenced `pValue` node which contains wanted access mode info.
The hackiest thing about this commit is probably `arv_gc_property_node_get_access_mode`. It can take both `AccessMode` and `pValue` properties.
The approach is quite experimental, but everything seems to work. Let me know what you think.
Edit: Forgot to mention that this topic was also discussed in #332
=> wip/genicam: implement 'AccessMode' and 'ImposedAccessMode' handling

.travis.yml
Force setuptools to be 49.6.0, as 50.0.3 makes meson fail with the
following error:
```
$ meson build
Traceback (most recent call last):
File "/usr/bin/meson", line 26, in <module>
from mesonbuild import mesonmain
ImportError: No module named 'mesonbuild'
```
=> travis: fix ci failure

src/arvgvdevice.c
Using MAX macro with g_get_monotonic_time() as one of parameters may
cause (and causes) a race because this is evaluated twice.
It lead to g_poll timeout being set to -1 causing infinite wait on
disconnected camera.
Very hard to reproduce. I use FAST-HEARTBEAT to make my software react for camera being plugged/unplugged faster.
After camera is lost the system polls for it once in a while in a separated thread.
I realized that arv_camera_new(camera_id) takes very long if the camera does not exists (but did exist previously). So what I am actually doing (after control-lost) is calling some read command (arv_camera_get_gain) and only once it succeeds I proceed with full re-initialization. This works fine but once in say 3 - 6 hours (!!!) with an attempt every 5 seconds the library freezes. I …
=> Fix _send_cmd_and_receive_ack timeout race

tests/arvnetworktest.c, tests/meson.build
A small utility for listing network interfaces. Sample output:
```
interface      proto          address             mask        broadcast
lo       IPv4        127.0.0.1        255.0.0.0        127.0.0.1
eth3       IPv4     169.254.64.1      255.255.0.0     169.254.64.1
eth3       IPv4    192.168.100.1    255.255.255.0    192.168.100.1
eth3       IPv4     192.168.2.12    255.255.255.0     192.168.2.12
virbr0       IPv4    192.168.122.1    255.255.255.0    192.168.122.1
docker0       IPv4       172.17.0.1      255.255.0.0       172.17.0.1
br-23a99ce39657       IPv4       172.18.0.1      255.255.0.0       172.18.0.1
```
=> Add simple test/utility program for listing network interfaces

src/arvnetwork.c, src/arvnetworkprivate.h
This should solve `inet_ntop` conflict described in https://github.com/AravisProject/aravis/issues/416#issuecomment-717220610 by @NerdToMars
=> mingw: only define inet_ntop conditionally, depending on _WIN32_WINNT

src/arvevaluator.c
Constants M_PI and M_E are not defined in standard C. This will result compilation errors under MinGW (x86_64-w64-mingw32-gcc, version 10.2.0). Fortunately glib defines G_PI and G_E so use those instead.
=> mingw: replace M_PI and M_E with G_PI and G_E

src/arvcamera.c
=> camera_set_trigger: ignore error if AcquisitionStart entry is not found

src/arvgvfakecamera.c
On some platform, gvsp packet send fails with EAGAIN, probably because at some point the socket buffer if full, and the socket is non blocking. Just make the gvsp socket blocking for now, it should fix #499.
=> fakegvcamera: make gvsp socket blocking

src/arvgvinterface.c
Some devices have a NULL string as the serial number. Use the MAC
address a a serial number fallabck in this case.
Fix #511
=> gvinterface: use MAC as serial number fallback

src/arvdebug.c
The former one doesn't need _POSIX_C_SOURCE, which is not defined when aravis is
compiled using mingw64.
Fix #525
=> debug: use localtime instead of localtime_r

.github/workflows/aravis-ci.yml, .github/workflows/aravis-mingw.yml, src/arvfakegvcamera.c, src/arvgvfakecamera.c, src/arvgvfakecamera.h, src/arvnetwork.c, tests/fakegv.c
And default to '127.0.0.1' instead of 'lo'.
Fixes #535
=> fakecamera: allow to specify listening interface by address

src/arvcameratest.c, src/arvmisc.c, src/arvmiscprivate.h, src/arvrealtime.c
1. Priorities are there, but I was never able to see them changed successfully.
2. The monotonic clock for windows should be more precise than libc functions, but I did not see much improvement in errors when I tested it back then. Aravis never calls that function, but it will be easier to do so if needed, plus the code does not get forgotten.
3. Disable buffering in arvcameratest.c for `stderr` and `stdout`; this might be just limitation of mingw (not sure) but in any case output would otherwise appear only when the program terminates.
=> Add thread priorities for windows, add high-precision clock for windows

tests/meson.build
Current `realtimetest.c` uses private functions from `arvrealtimeprivate.h` that are Linux RealtimeKit specific. Therefore disable this test on other platforms.
Potentially another more high-level test could be written that uses public `arv_make_thread_realtime` and `arv_make_thread_high_priority` functions. That could be enabled on all platforms.
=> tests: Compile 'realtimetest.c' only on Linux.

src/arvcamera.c
The feature 'AcquisitionFrameRateEnable' is not available on Basler dart family models 
and has to be used with prior check for availability.
( any value in feature 'AcquisitionFrameRate'  works as a clipping value for the frame rate )
=> arv_camera_set_frame_rate: AcquisitionFrameRateEnable is not available on some Basler camera models

src/arvmisc.c, tests/genicam.c
Someone at GlobalSensorTechnology thought it was a good idea to pretify the
genicam data url, hence url like this one:
'Local: guide_gige_test.zip; 00010000; 06c5'
=> genicam: ignore leading spaces in local data url

src/arv-test.cfg, src/arvcamera.c, src/arvtest.c
It looks like some of their devices require to set the FrameRate before enabling
it.
=> camera: try to improve LucidVision support

.lgtm.yml
Default meson version is 0.51, while we need 0.55 now.
=> ci: LGTM configuration file

.github/workflows/aravis-mingw.yml, .github/workflows/aravis-msvc.yml, meson_options.txt, src/arvgvstream.c, src/arvparamsprivate.h.in, src/meson.build
See [issue 616](https://github.com/AravisProject/aravis/issues/616)
=> gvstream: improve performance of receiving loop (issue #616)

src/arvnetwork.c, src/arvnetworkprivate.h, src/arvrealtime.c
Add FreeBSD support and probably fix other OSes to not show network interfaces without BROADCAST flag.
=> Add FreeBSD support

docs/reference/aravis/building.md
Needed to install these packages in order to support all of the build options on Fedora 34/35.
=> Add dependencies for Fedora

src/arvuvdevice.c
These changes fix the bug described in #622.
=> Lock usb cmd transfer to prevent reply mix up

src/arvgccategory.c, src/arvgcfeaturenode.c, tests/data/genicam.xml, tests/genicam.c
=> gccategory: accept all property nodes

src/arvgvcp.c
arv_gvcp_packet_new_packet_resend_cmd() allocates a correct memory size for both
standard and extended ID modes. But a size value inside header is not correct
in case of an extended ID mode. Value is always like for standard ID mode.
=> fix PACKETRESEND size in header for extended ID mode

viewer/data/arv-viewer.appdata.xml.in
This pull request update the path to the aravis icon.
While github in general redirects _master_ links to _main_, AppStream doesn't know about that, then the icon is not retrieved.
Found in packaging for Debian.
Thanks for considering it.
=> Update path to aravis icon: fix AppStream warning.

src/arvcamera.c
In the process of supporting Imperx cameras, I will need to make the usage of TriggerSelector optional.
But it appears that the implementation of `arv_camera_disable_all_triggers` introduced 8 months ago is the same as the `arv_camera_clear_triggers` that was already there.
=> camera: remove duplicate of arv_camera_clear_triggers

src/arvbuffer.c
This allows a callback to not be passed from an FFI, e.g. PyGObject.
=> arvbuffer: fix declaration of user_data_destroy_func

gst/gstaravis.c, gst/gstaravis.h
Define maximum latency and GST_CLOCK_TIME_NONE to prevent timeouts.
Potential fix for #528.
All gstreamer sources must be synchronized with the gstreamer clock.
Since aravissrc is a live source it can't give reliable increasing timestamps and instead works with durations.
Ideally that would mean first timestamp (0) + duration of frame. New timestamp + duration of frame, etc.
Since we cannot know what the duration of a frame is (some come faster, some slower, thus never being 100% accurate) gstreamer wants to know a latency range. 
This patch defined the latency as min=framerate and max=GST_CLOCK_TIME_NONE.
That basically says expect the next buffer between average duration and any given time in the future after that,
users more than enough time to trigger, extended exposure times, etc.
=> gst: Add GstQueryLatency handling

src/arvgcenumeration.c
Fixes #678
Removing this check, we will not know anymore if the value returned by the
device is a valid one. But it is the device fault, as on write the availability
is still checked.
And know we avoid an infinite loop on some devices like the one in the issue
report.
=> gcenumeration: don't check enum entry avalability on read

.github/workflows/aravis-msvc.yml
in msvc pipeline
1. disabled strawberry perl and added pkg-config on conanfile
2. enabled gst-plugin
---
1. somehow the latest meason does not support pkg-config bundled with strawberry perl. So removed directory under `C:\Strawberry\perl`
Runner image of [Microsoft Windows Server 2019 Datacenter](https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md) has Perl 5.32.1 as a default and it is located under `C:\Strawberry\perl`
2.  pkg-config installed as dependencies with conan now can find glib-2.0 and gst-plugins-base is successfully installed
=> ci: enable gst-plugin in msvc pipeline

src/arvcamera.c, src/arvcamera.h, src/arvdevice.c, src/arvdevice.h, src/arvfakedevice.c, src/arvfakestream.c, src/arvfakestreamprivate.h, src/arvgvdevice.c, src/arvgvstream.c, src/arvgvstreamprivate.h, src/arvstream.c, src/arvuvdevice.c, src/arvuvstream.c, src/arvuvstreamprivate.h, tests/fake.py, tests/python/arv-stream-callback.py
This PR should fix the crash seen in #453. The crash was caused by `ArvStreamCallback` only living for the time of the call to `arv_camera_create_stream` because of `(scope call)`. Using `(scope notified)` allows us to control the lifetime of the callback.
Also added a small Python sample showing how to use stream callback.
:warning: GObject & GLib noob here, careful review required.
=> Fix crash when using stream callback in Python

src/arvgvdevice.c, src/arvgvspprivate.h
The computation of the expected test packet was wrong on some platform, so don't use sizeof.
Also, GevSCPSPacketSize increment was not correctly take into account.
And finally, don't limit the precision to 16 but to increment instead. I fear forcing the precision may conflict with cameras with increment not a divisor of 16 (which would be surprising, but who knows (yes, the GigEVision documentation, but we can not use it :( )).
=> gvdevice: improve auto packet size

src/arvuvstream.c
It happens arv_uv_device_bulk_transfer succeed, but with no data transferred. Check the number of transferred bytes before trying to interpret the buffer content.
Fixes #737
=> uvstream: check transferred size before using the result

.gitignore
Add .vscode dir to .gitignore file.  This helps 'git status' remain clean for folks who use vscode with workspace-specific settings.
=> Add .vscode dir to .gitignore file

src/arvgcport.c
SC130ET3 is one of our products. I'd like to my camera works on aravis. I hope that aravis project would accept this change.
=> added port legacy info for kowaOptronics SC130ET3

src/arvgvdevice.c
When the increment of GevSCPSPacketSize is not correctly returned by the device, the difference between the computed packet size and the actual packet size can lead to an infinite loop.
Fix #755
=> gvdevice: fix infinite loop in auto packet size

src/arvgcenumeration.c
This reverts commit 93d536bb26fa3e6af6e1d2ced60f0b8d295e2df5.
Fixes #765
=> gcenumeration: revert bogus entry ordering commit

.github/workflows/aravis-msvc.yml, src/arvuvdevice.c
It is 8 byte long according to wireshark u3v dissector.
Fixes #578
=> uvdevice: fix srbm_u3vcp_capability register size

src/arvcamera.c, src/arvcamera.h
Hi,
I have the following fixes running successfully in my project as a patch and am now proposing to add these upstream so they can be included in a future release (and I can just update my buildroot's Aravis version).
This PR fixes the following:
- Vendor specific quirks to set the frame rate limit were only checked when frame rate limiting must be enabled.
- When wanting to disable frame rate limiting by calling arv_camera_set_frame_rate(cam,  **0**, NULL), the vendor specific quirks were not applied.
- This was observed on a FLIR and Basler camera, where the Basler works out of the box, but the the FLIR one needed a quirk to disable frame rate limiting.
I have proposed to fix this by extracting the code with the vendor specific quirks to a new method …
=> Frame rate limit disabling also need vendor specific quirks

src/arvcamera.c, src/arvcamera.h, src/arvgvspprivate.h, src/arvuvcpprivate.h, src/arvuvspprivate.h
This fixes a couple of warnings I got when locally building aravis. It also casts to the correct return types at various places.
Another noticeable change is that `arv_camera_dup_available_black_levels` was wrongly named in the corresponding `arvcamera.h`.
=> Fix various warnings

src/arvgvdevice.c
=> gvdevice: allow auto packet_size to be equal to max size

docs/reference/aravis/porting-0.8.md
I've found a (semantically) broken link in docs. `glib-Error-Reporting.html` is now named `error-reporting.html` and it is in GTK docs and not GNOME developer docs. I've fixed it to help finding the error reporting reference more easily.
Thanks for the project maintenance!
=> doc: fix link to GLib error reporting docs

src/arvuvdevice.c, src/arvuvstream.c
```
This fixes compiling with clang 16 in 32 bit mingw environment.
Here is the compiler error:
../src/arvuvstream.c:303:3: error: incompatible function pointer types passing
'void (struct libusb_transfer *)' to parameter of type 'libusb_transfer_cb_fn'
(aka 'void (*)(struct libusb_transfer *) __attribute__((stdcall))')
[-Wincompatible-function-pointer-types]
```
=> Add calling convention to libusb callback functions

.github/workflows/aravis-linux.yml, .github/workflows/aravis-macos.yml, .github/workflows/aravis-mingw.yml, .github/workflows/aravis-msvc.yml
Node.js 12 actions are deprecated. These actions are using Node.js 16.
=> ci: update GitHub Actions versions

src/arvgcport.c
Adds EVK HELIOS to ArvGvLegacyInfos struct in arvgcport.c
=> Add support for EVK Helios cameras (Genicam 1.0 legacy mode)

src/arvnetwork.c
This patch allows Aravis to connect to cameras over POINTOPOINT IP links.  Broadcasts are not expected to work, but unicast does.  This allows connecting to cameras across a VPN, or PPPoE network.  This addresses issue #823
=> Don't ignore POINTOPOINT interfaces on UNIX family OSes

src/arvdevice.c
Previously  the result was casted to a boolean, always returning `ARV_GC_ACCESS_MODE_RO` or `ARV_GC_ACCESS_MODE_WO`.
Now it returns the correct enum.
=> Fix feature node access mode retrieval.

src/arvbuffer.c, src/arvbuffer.h, src/arvbufferprivate.h, src/arvuvspprivate.h, src/arvuvstream.c
The image data can be retrieved using the multipart or image accessors for now.
=> usb3vision: handle gendc payload

src/arvgentldeviceprivate.h, src/arvgentlsystemprivate.h, src/arvmiscprivate.h
Reverts AravisProject/aravis#851
This is not needed when only using a c compiler.
=> Revert "Add GenTL namespace when using respective code."

src/meson.build
The header `arv.h` includes `arvnetwork.h` but this file gets not installed. This PR adds `arvnetwork.h` to `library_headers` to fix the issue.
=> install arvnetwork.h header

src/arvgcport.c
This allows using a NIT WiDy SenS 640 camera with aravis.
=> add NIT NSC1601GIGE to Genicam 1.0 legacy exception list

src/arvcamera.c
Previously for unknown and a couple of other cameras the actual flag value was ignored and always set to true.
=> Fix passing of AcquisitionFrameRateEnable boolean flag.

src/arvcamera.c
This way we can support a wider range of cameras with e.g. different naming schemes for the `AcquisitionFrameRateEnable` feature.
=> Reuse arv_camera_set_frame_rate_enable method when setting trigger. 

src/arvcamera.c, src/arvcamera.h
This is corresponding to the arv_camera_set_frame_rate_enable method and includes some camera-specific quirks.
See also #876 for some other cleanups.
=> Add arv_camera_get_frame_rate_enable method.

src/arvgvdevice.c, src/arvgvstream.c
=> gvstream: put a lower limit to socket buffer size

src/arvxmlschema.c
As of https://gitlab.gnome.org/GNOME/libxml2/-/commit/61034116d0a3c8b295c6137956adc3ae55720711, the error struct in the callback is const
I could also add a cast to `xmlStructuredErrorFunc` on the use sites so it compiles against both new and old versions of libxml without warnings/errors.
=> xml: make error struct constant

src/arvcamera.c
Previously irrespective of whether a trigger was set or not the frame rate was tried to be disabled. However, this failed (at least for an Allied Vision-Alvium G1-1240c) if already a trigger was set, causing the whole set_trigger call to fail.
The failure was actually introduced with https://github.com/AravisProject/aravis/pull/877/files#diff-d7be5be1f918127f4161b7f5a654290347f3334e434d14a61eb04e013b85dd99R1388 where the local_error was for the first time checked (Before that it was set but ignored).
This also fixes a bug where the wrong error pointer was checked in arv_camera_get_frame_rate_enable.
=> Make sure to only disable frame rate if necessary.

src/arvdevice.c, src/arvdevice.h
The purpose of this PR is to be able to generate a corresponding [FFI binding in Rust](https://docs.rs/aravis/latest/aravis/) without needing `mut` on the buffer to be written.
=> device: use const void* in `arv_device_write_memory`

src/arvgvdevice.c
Without the fix after camera creation, `DeviceReset`, device list update, and camera recreation a segmentation fault happened because of a null pointer when destructing the original camera.
=> Fix finalization of gv device.

src/meson.build
The corresponding sources and headers were defined, but not the private headers.
=> Add missing private header.

.github/workflows/aravis-mingw.yml
gst-plugins-goods and libusb seems to be missing:
```
Enter a selection (default=all): error: target not found: mingw-w64-i686-gst-plugins-good
error: target not found: mingw-w64-i686-libusb
```
=> ci: disable mingw32 for now

src/arvmisc.c, src/arvmisc.h, tests/misc.c, viewer/arvviewer.c
This camera send Mono16 in big endian, while it should send little endian data. Use the right gst caps string according to an exception list.
=> gst: workaround for BlackFly U16 pixel endianness issues

viewer/data/meson.build, viewer/data/org.aravis.viewer.appdata.xml.in
Dear aravis maintainers,
this pull request fixes a [bug reported](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1078195) during debian packaging, applying the patch offered by @petterreinholdtsen.
It corrects appstream metainfo validation errors, adding missing `<p>` to description and making sure file name match ID.
Also it uses the new `metainfo.xml` ending replacing the obsolete `appdata.xml` ending.
Thanks for considering it.
=> aravis-tools: Correct appstream metainfo description and file name

meson.build, src/arv-test.cfg, src/arv-v4l2.xml, src/arvcameratest.c, src/arvdebugprivate.h, src/arvmisc.c, src/arvstream.c, src/arvtest.c, src/arvuvstream.c, src/arvv4l2device.c, src/arvv4l2deviceprivate.h, src/arvv4l2interface.c, src/arvv4l2misc.c, src/arvv4l2miscprivate.h, src/arvv4l2stream.c, src/meson.build, tests/meson.build, tests/v4l2test.c, viewer/arvviewerresources.xml, viewer/icons/gnome/scalable/devices/aravis-v4l2-symbolic.svg
=> v4l2 support

.github/workflows/aravis-linux.yml, .github/workflows/aravis-macos.yml, .github/workflows/aravis-mingw.yml, .github/workflows/aravis-msvc.yml
```
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```
=> ci: fix setup related meson warning

src/arvgvstream.c
The buffer we are processing here is not yet stored in frame data. Fix #941
=> gvstream: fix wrong access to not yet initialized frame data

tests/genicam.c
Currently, this function leads to `SIGBUS` crash at armv7l architecture without `CONFIG_ALIGNMENT_TRAP` kernel option.
=> Fix unaligned access in tests/genicam.c

src/arv-test.cfg, src/arvchunkparser.c, src/arvchunkparser.h, src/arvtest.c
On some devices, chunk access requires a change of a local feature value. For example:
```
<Enumeration NameSpace="Standard" Name="ChunkComponentSelector">
<Visibility>Expert</Visibility>
<EnumEntry NameSpace="Standard" Name="Range">
<Value>0</Value>
</EnumEntry>
<EnumEntry NameSpace="Standard" Name="Normal">
<Value>1</Value>
</EnumEntry>
<EnumEntry NameSpace="Standard" Name="Texture">
<Value>2</Value>
</EnumEntry>
<Value>0</Value>
</Enumeration>
<Float NameSpace="Standard" Name="ChunkScan3dCoordinateOffset">
<Visibility>Expert</Visibility>
<ImposedAccessMode>RO</ImposedAccessMode>
<pValue>ChunkScan3dCoordinateOffsetRegister</pValue>
<Min>-3.40282e+38</Min>
<Max>3.40282e+38</Max>
<Inc>1e-6</Inc>
<DisplayPrecision>6</DisplayPrecision>
</Float>
<FloatReg NameSpace="Custom" …
```
=> chunkparser: allow to set string and integer features

src/arvgcintegernode.c
It seemed strange to me to check the local_error variable for NULL when no one was working with it. I think something like this was meant
=> arv_gc_node_set_integer_value. error to local_error

src/arvgvspprivate.h
Using the named constants clarifies intent, avoids magic numbers and improves type safety.
=> gvsp: replace magic 0 with explicit constants
