AravisProject/aravis

- src/arvgvdevice.c
This fixes a problem that occurs when the camera is under high pressure
and not feasible to acknowledge gvcp requests immediately
(Or the gvcp_timeout_ms is to low).
Description:
A gvcp command was sent by _read_memory(), _write_memory(),
_read_register() or _write_register(). Waiting for the acknowledge
packet (with the corrosponding packet id) times out.
After that the camera sends this acknowledge package which will not be
processed by now. Therefore it remains in the socket receive buffer.
Impact:
Following gvcp commands will also fail because they get the wrong
acknowledge package
(the old one with wrong packed id => unexpected answer).
Its not possible to recover from that state. Old acknowledge packages
will allways remain in the receive buffer.
Therefore gvcp commands will fail by …
> gvcp: flush socket receive buffers before sending new commands

- README.md
I got various errors from `./configure` and `make`, and needed to add these commands to get it all running smoothly.
> Update Mac build instructions to fix errors

- README.md
Following up on #131 (thank you for the clarification there). I believe this piece of text made it into the final commit by accident.
> Delete orphaned sentence in README

- src/arvgvdevice.c
As wished in Issue #199, here is a pull request with the fix for packet size negotiations.
> Query device for GevSCPSPacketSize adjustments

- src/arvuvdevice.c
> Added sanity checks for usb camera initialization

- src/arvgvfakecamera.c
- src/arvgvfakecamera.h
I needed this to write a custom gv fake camera program to support the work I'm doing.
> Added accessor method for the camera class of ArvGvFakeCamera

- src/arvfakecamera.c
> Add comment block to arv_set_fake_camera_genicam_filename as per code

- src/arvcamera.c
Just a minor clarification, I was assuming the timeout is in seconds, fortunately I checked before using a value of 1 :-)
> Clarify scale of the timeout variable.

- src/arvuvdevice.c
> uvdevice: unref device upon failure

- viewer/meson.build
> viewer: Fix locale directory

- viewer/arvviewer.c
refactoring: splitting too long 200 SLOC function start_video
> Set camera widgets

- gst/gstaravis.c
This adds error handling to gst_aravis_start to fix #346.
This does not add error handling to caps, stop and properties, but I do not see them being that critical.
> gst: Error on start if no camera found

- gst/gstaravis.c
This adds error handling to gst_aravis_start to fix #346 on aravis-0-6 branch.
This is a backport of #347.
> gst: Error on start if no camera found for aravis-0-6 branch

- src/arvgcstringregnode.c
Before this patch all strings were written without null-terminator to the device. This may cause issues when writing over longer strings in camera memory and fails completely when writing zero-length strings as it would amount to writing zero bytes to camera registers.
New string writing method first obtains maximum allowed string length. If the string length is more than allowed then the function returns with an error. Otherwise the string is written to the memory with null-terminator as long as there is enough space. If string length is equal to maximum allowed length then null-terminator is omitted.
> Better string register writing support.

- .travis.yml
Added ppc64le power support to the travis.
> Adding ppc64le support

- src/arvevaluator.c
> pVariable names can contain dots

- src/arvgvdevice.c
- src/arvmisc.c
- src/arvmiscprivate.h
- tests/genicam.c
- tests/loadhttptest.c
> gvdevice: fix parsing of local file with query string

- src/arvgvfakecamera.c
> fakecamera: fix listening interface selection

- src/arvnetwork.c
Fix for compiling windows version.
> Fixed misspelled variable name.

- src/arvgvdevice.c
- src/arvuvcp.c
- src/arvuvcpprivate.h
- src/arvuvdevice.c
> uvdevice: factorize read/write code

- src/arvmisc.h
- src/arvnetwork.c
To be merged when glib 2.68 is released.
> Fix glib deprecation warning

- src/arvdebug.c
And modernize the output a bit.
> debug: timestamp debug output

- .github/workflows/aravis-mingw.yml
Preview only; aravis:main / fakegv test fails for some unknown reason.
> Action for automated mingw build

- README.md
related to https://github.com/AravisProject/aravis/issues/533
> Document compilation for Windows (incl. cross-compilation)

- src/arvgvfakecamera.c
- src/arvnetwork.c
- src/arvnetworkprivate.h
using the new network functions - I think it makes the logic clearer, without the looping over interfaces which is pushed into those network functions. I uses the new master logic which you added yesterday, which proceeds even if the primary sockets (GVCP and GVSP) fail to bind.
> Streamline fake device creation

- .github/workflows/aravis-ci.yml
- .github/workflows/aravis-mingw.yml
- meson.build
- viewer/arvviewer.c
- viewer/main.c
In addition to the current raw data output. There is no need for notify now, the
dependency is removed.
> viewer: save snapshot to png and jpeg

- src/arvgvinterface.c
I *think* this will fix #364 .
> use proper broadcast addresses in discovery for each network

- src/arvgvinterface.c
> gvinterface: use local brodcast, and fallback to directed on error

- src/arvgc.c
- src/arvgcprivate.h
- src/arvgcregisternode.c
- src/arvtest.c
- src/meson.build
> Track register cache errors in arv-test

- src/arvcamera.c
I have made the TriggerSelector feature optional in order to support Imperx camera POE-C series missing this feature.
But I have several questions:
- Is it ok to check if the feature is available or should I check the camera model as done elsewhere in `arvcamera.c`?
- What is your prefered indentation method? This file is mixed between tabs and 8 spaces
Do you want to change progressively from tabs to spaces ?
The clang-format file mention tabs but the editorconfig file uses spaces.
Note that I could have checked the number of triggers returned by the function `arv_camera_dup_available_triggers` but when `TriggerSelector` is not available, the `local_error` is not `NULL`.
> camera: allow to use camera without TriggerSelector feature

- src/arvgcport.c
Some devices advertise a schema version 1.1.0 but still use legacy legacy memory access methods.
This PR introduces a list of devices that is checked to chose the right method.
This is only a draft for now, any comments are welcomed.
> arvgcport: add a list of devices using legacy infos

- src/arvcamera.c
- src/arvcamera.h
- src/arvgvdevice.c
- src/arvgvdevice.h
This pull request adds some APIs for GigE Vision IP setting.
Fix #479
> gigevision: add APIs for GigE Vision IP setting

- src/arvinterface.c
- src/arvinterface.h
> interface: avoid use of msvc reserved interface keyword

- src/arvcamera.c
Feature ExposureTime is not available if ExposureMode is not set to Timed
so check for ExposureMode in arv_camera_is_exposure_time_available.
I don't know for the other series so change the behavior on series instead of vendor.
> camera: Add workaround to set exposure time and check if available on Imperx Cheetah

- src/arvuvdevice.c
- src/arvuvinterface.c
> usb: better libusb error handling

- docs/reference/aravis/building.md
Related to #748 
Just a few minor fixes.
> Update docs about Meson

- src/arvfakecamera.c
- src/arvfakecamera.h
- src/arvfakedevice.c
- src/arvgvdevice.c
- src/arvuvdevice.c
> genicam: store genicam URL in ArvDomDocument URL property

- meson.build
- meson_options.txt
- src/arv-v4l2.xml
- src/arv.h
- src/arvfeatures.h.in
- src/arvresources.xml
- src/arvsystem.c
- src/arvv4l2device.c
- src/arvv4l2device.h
- src/arvv4l2deviceprivate.h
- src/arvv4l2interface.c
- src/arvv4l2interface.h
- src/arvv4l2interfaceprivate.h
- src/arvv4l2stream.c
- src/arvv4l2stream.h
- src/arvv4l2streamprivate.h
- src/meson.build
Interface to Video for Linux devices
> V4L2 support

- src/arvnetwork.c
> network: add missing include

- src/arvgentlinterface.c
> gentlinterface: return the first available device if id == NULL

- gst/gstaravis.c
- gst/gstaravis.h
> gst: add gamma property

- src/arvgvfakecamera.c
- src/arvgvsp.c
- src/arvgvspprivate.h
These are the changes needed to fix issue #995
> Add height value to data0 trailer packet

- src/arvgcport.c
Adding Xenics Wildcat to the ArvGvLegacyInfos struct.
> Add Xenics Wildcat to ArvGvLegacyInfos
